### ISSUE TITLE
No "Please wait" page is shown to the user during lookup.

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#15]

**Comment by redwire** [comment]
I've been running my own tests for a while now and I don't have any trouble with this.
I recall that, when we had spoken previously, you mentioned that you were having the cache server make requests to the transport server and I explained that that's now how it should work. 
The cache server should respond to a lookup request from CeNo client as soon as possible, because CeNo client only serves "please wait" when it knows it has to wait for the transport server to finish making a new bundle (which is potentially the most contentious part of the system).
Given this, is this still an issue?  There may still be some delay before "please wait" is served while the cache server does a lookup to see whether a bundle exists or not, but the protocol doesn't involve sending anything to the user until a response from the cache server is received.

**Comment by redwire** [comment]
This is effectively solved by the implementation of the new protocol.
