### ISSUE TITLE
Update ceno-node to implement basic functionality

### ISSUE THREAD

**Issue by billdoran** [equalitie/ceno#2]
- Allow bundling of very basic pages
- For non-bundleable resources ensure that entity is proxied
- If considering replacing sections of code with different/improved libraries document changes with short justification here to allow discussion

**Comment by redwire** [comment]
In Issue #4 I outlined my proposal to drop PhantomJS to do some more manual resource handling. I proposed Cheerio and JSDOM as options for libraries to handle resource identification and HTML manipulation (Data URI replacement).  After doing some reading about both, I would like to propose we favor [Cheerio](https://github.com/cheeriojs/cheerio) to [jsdom](https://github.com/tmpvar/jsdom) as it purports to be much faster and simpler. JSDOM does a lot of extra work in actually building a DOM tree so that server-side testing of client code can be done, but we really only need the kind of functionality JQuery offers for navigating HTML code and doing simple manipulation. This appears to be something Cheerio excels at.

As for the choice between [superagent](https://github.com/visionmedia/superagent) and [request](https://github.com/request/request) I would like to ask for feedback.
We already use request in the bundler and it appears to offer some really fancy client functionality, but I worry that most of the functionality isn't really required for our purposes. Superagent, on the other hand, appears to really focus on providing a nice API for crafting relatively commonplace HTTP requests, which leads me to believe it might be better suited to doing the kind of manual resource management I discussed since we aren't as concerned with simulating a complicated client as we are likely to just want to have fine-grained control over what our requests actually look like.
