### ISSUE TITLE
Cached bundles include URLs to the out-of-freenet Web

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#26]
A mechanism is needed for rewriting external links within bundles in a way that, when clicked, they will be requested by CeNo.
A solution is to prefix external links with "http://127.0.0.1:3090/?url="

**Comment by billdoran** [comment]
I actually, think this should be ok because the ceno-client will be used
as a proxy via the user's browser so all request will get pushed through
our system.

**Comment by misaakidis** [comment]
We have to protect users who request the cached bundle directly from freenet using the USK.

**Comment by billdoran** [comment]
Interesting point. Let's think through the scenario.
If I request a page directly from freenet using USK how do I get the USK and how do I know which client proxy I want to use.
I think this may be an unsupported feature for the moment. It is possible I am missing something obvious - if I am tell me so :)

**Comment by redwire** [comment]
Gentlemen, I bring good news!
I have long-since included in Bundler the functionality to replace links in a page before it is served and so it is very much possible to have this problem solved by the transport server. You can learn a little about how this feature works in the [basic usage](https://github.com/equalitie/bundler#basic-usage) section of the Bundle README.
If there is a generic sort of formula we can use to replace URLs, this is a piece of cake. By formula, here, I mean any (efficient) algorithm to carry out a transformation of any given URL (given the base URL of the site, such as http://google.com and the resource URL) to the kind of URL we want on the page.
Let me know how this would look and I can prepare to write something any time.

**Comment by redwire** [comment]
This has been discussed at length recently.
Since the user is running CeNo client as a web proxy, any requests to resources outside of Freenet will be proxied normally and end up being captured by the freenet plugin.
