### ISSUE TITLE
Switch to TCP-based protocol

### ISSUE THREAD

**Issue by redwire** [equalitie/ceno#31]
Following the protocol outlined in my [second proposal](https://github.com/equalitie/ceno/blob/master/ceno-node/doc/CeNoProtocol2prop2.md) for improving the way that the parts of CeNo interact, the following things need to be done (in order).

1. [x] Complete rewrite of CeNo Client
2. [x] Modify the Transport Server to adhere to the new protocol
3. [x] Write a new test cache server adhering to the new protocol
4. [ ] Modify the actual Cache Server to have it adhere to the new protocol - For @misaakidis 

We will be using the simplest version of the protocol, at least for now, which is directly specified in the proposal.

**Comment by redwire** [comment]
Switched assignment to @misaakidis as I have completed and thoroughly tested the implementations of the client and transport server.

**Comment by vmon** [comment]
NB. I change Transport Server -> Bundling Server and TS->BS to reduce
confusion.

The main reason for moving from HTTP to another protocol is well explained here:

"Because we are no longer working with HTTP itself, we do not have to
worry as much about timeouts."

For example, either CS / BS can write the bundle directly in the socket
opened by CC to request it.

This benefit vanishes partially, under current assumption (fact) that
CS->BS connection is one way. (I personally thinks that even if Freenet
was not forcing this assumption, it was a good assumption to help the
BS's anonymity).

This assumption makes steps 5 and 7 impossible in "Lookup Failure" scenario:

1. CC requests CS lookup a bundle. [LOOKUP <url>] - open
2. CS informs CC that no bundle exists for <url>. [RESULT not found]
3. CC acknowledges, and closes the connection. [OKAY] - close
4. CC requests BS create a new bundle. [BUNDLE <url>] - open
5. BS informs CC when the bundle is complete. [COMPLETE]
6. CC acknowledges and prepares to receive bundle data. [READY]
7. BS sends bundle data to CC. [_ bundle] - close
8. BS asks CS to store the new bundle. [STORE url] - open
9. CS acknowledges and prepares to receive bundle data. [READY]
10. BS sends bundle data to CS. [_ bundle] - close

So, they need to be replaced by some "periodic check" or something else
(Prometheas had something in mind), in that case AFAIU HTTP is adequate
for these tasks.

However CC<->CS connection is two way and they benefit from non-HTTP
type communication in steps 3. And also in step, 2 and 4 of the success
scenario.

1. CC requests CS lookup a bundle. [LOOKUP <url>] - open
2. CS informs CC that a bundle exists for <url>. [RESULT found]
3. CC acknowledges and prepares to receive bundle data. [READY]
4. CS sends bundle data to CC. [_ bundle] - close

The question is that is that enough reason to move away from HTTP.

We have following option for the implementation:

1. CC is not a server.

1.1. - (current) HTTP for CC->BS. Periodically check of the CS for the result.
     - HTTP for CC->CS. Periodically check of the CS for the result.

1.2. - HTTP for CC->BS: Periodically check of the CS for the result.
     - Socket for CC<->CS.

1.3. - Socket for CC->BS. Periodically check of the CS for the result.
     - Socket for CC<->CS.

2. CC is a server.
2.1. - HTTP for CC->BS. Periodically check of the CS for the result.
     - HTTP for CC->CS and HTTP CS->CC.

I prefer 1 over 2 because making CC a server seems too much complication
(js in browser doesn't support server, it might force you to install
nodejs on the client).

Between 1.1,1.2 and 1.3 approaches, I think it is the implementers
choice. First glance 1.2 seems not very useful. If you already have a
way of dealing with sockets in your code then you probably better to
stick with it, but I might be wrong.

For between 1.3 and 1.1, my knowledge of Javascript isn't enough, but I
think you need  WebSocket or something like that if you want in browser
client (having a minimal client model in mind).

Prometheas has a point in preferring 1.1 over 1.3 that HTTP
implementation is available and it make the subsequent implementation
for other network rather than Freenet much easier.

Considering lack of time till the end of project, I would recommend to
stick with 1.1. But we should discuss the long term plan.
