### ISSUE TITLE
Refining the communication protocol of CENO components

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#33]
Original version: https://github.com/equalitie/ceno/blob/386312cec7d9030927de292135a0d45cadbd2466/ceno-node/doc/CeNoProtocol.md

There is a need to:
* decouple CENO from underlying technologies (e.g. transport or caching network)
* limit "state" sharing between components

#### Client Side
**CENO Client (CC)** is the client-side HTTP proxy server (browser plugin) that the User proxies their requests through.
**Bundle Retrieval Server (BRS)**  retrieves and serves bundles from the underlying storage medium.
**Request Sender (RS)** is responsible for sending request messages to the bridge.
#### Bridge Side
**Request Receiver (RR)** receives request messages for making a bundle.
**Bundle Server (BS)**  is the service that creates a bundle for a given URL.
**Bundle Inserter (BI)** inserts bundles in the storage medium.

Any of the underlying technologies might provide the functionality of multiple agents. For example, in the case of freenet, the client-side plugin might server as BRS and RS at the same time.
Also, agents are responsible for keeping their own state and act accordingly to interactions with other agents. As an example, RS should only send a single freemail for a URL no matter how many "send request to the bridge" messages receives from the CC.

**Comment by misaakidis** [comment]
## Agents Interaction
### Client Side
Step | Description                                            | Message
-------|--------------------------------------------------|-------------------
1 | CC requests BRS lookup a bundle. | `[GET <BRS>/lookup?url=<url>]`
2 | BRS makes a lookup at the local cache
2.1 | If local lookup is successful, BRS returns the data | `[write {"complete": true, "found": true, "bundle": <bundle>, "creationDate":<bundle creation date>}]`
2.2 | If data was not found in the local cache, BRS begins a background lookup request in the distributed cache | `[write {"complete":false}]`
3 | CC shows a "Looking up in the distributed cache" page to the user
4 | "Looking up in the distributed cache" page refreshes and CC makes a new request to BRS | `[GET <BRS>/lookup?url=<url>]`
4.1 | Lookup request is still in progress |  `[write {"complete":false}]`
4.2 | Lookup request has been completed
4.2.1 | Request was successful and the bundle is available | `[write {"complete": true, "found": true, "bundle": <bundle>, "creationDate":<bundle creation date>}]`
4.2.2 | Request failed and data does not exist in the distributed cache | `[write {"complete": true, "found": false}]`
5 | CC shows a "Requesting bundle from the bridge" page to the user
5.1 | CC initiates the process of requesting a bundle from the bridge | `[GET <RS>/fetch?url=<url>]`
5.2 | RS sends a message to the bridge for a bundle to be made and inserted for the given URL
6 | "Requested bundle from the bridge" page refreshes and CC makes a new lookup request to BRS (Step 1) | `[GET <BRS>/lookup?url=<url>]`

* The process terminates as soon as the bundle data are returned to the CC {"complete": true, "found": true} (Steps 2.1 and 4.2.1)
* All HTTP requests are expected to return in short time and therefore can be handled synchronously.
* In order to send a message for a new bundle to be made to the bridge as soon as a new URL is requested by CC, BRS writes `[write {"complete": true, "found": false}]` on Step 4.1.
* "creationDate" JSON value is used to check if the bundle received is stale. In that case, CC shows the bundle to the user and prompts her/him if she/he would like to get a new version. If the user agrees, protocol repeats steps starting from Step 5.

**Comment by vmon** [comment]
Client Side
Step | Description                                            | Message
-------|--------------------------------------------------|-------------------
1 | CC requests LCS lookup a bundle. | `[GET <CRS>/lookup?url=<url>]`
2 | LCS makes a lookup at the local cache
2.1 | If local lookup is successful,
2.1.1 |LCS returns the data | `[write {"complete": true, "found": true, "bundle": <bundle>, "creationDate":<bundle creation date>}]`
2.1.2 | End
2.2 | If data was not found in the local cache, LCS begins a background lookup request in the distributed cache | `[write {"complete":false}]`
2.2.2 | LCS goes to 1.
2.3. If request failed and data does not exist in the distributed cache | `[write {"complete": true, "found": false}]`
2.3.2 | CC initiates the process of requesting a bundle from RS | `[POST <RS>/fetch?url=<url>]`
2.3.3 | RS starts the process of populating the cache
2.3.5 | CC goes to 1


Optional protocols:

Bridge Side
1 | RR receives the url from RS
2 | RR request url from BS  | `[GET /?url=<url>]`
3 | BS respond with the Bundlle 
4 | RR send the Bundlle to RCS 

RS-LCS/RR-RCS communication protocl:
1. RS/RR receives the response
2. RS/RR posts to LCS/RCS the requested content | `POST <LCS> /response data`
3. LCS/RCS inserts the response into the cache

Comments:
* Changing BRS to LCS (Local Cache server) because
1. caching in censor area is part of definition of ceno.
2. because we are thinking about the possiblity of RS receiving the bundle and post data to LCS, so it is not only rectrival.

**Comment by redwire** [comment]
I've updated the [official specification document](https://github.com/equalitie/ceno/blob/master/ceno-node/doc/CeNoProtocol.md) to contain most of the changes you have described here.

Could I get some clarity on the interaction between the request server and request receiver? Point 5.2 in @misaakidis's first table just says that a message is sent. For now, I have duplicated the request made to the RS to the RR [see points 5 and 6](https://github.com/equalitie/ceno/blob/master/ceno-node/doc/CeNoProtocol.md#lookup-failure)

If you would like to suggest some changes to the protocol spec I have written, it might be best to submit a pull request so I can make sure the markdown is good and so that we can comment on particular changes, if that's not too much effort.

**Comment by misaakidis** [comment]
Point 5.2 (Step 6 in the official documentation) is an abstract description of RS's internal mechanism for signaling RR on bridge to create a new bundle. Since RS might use protocols other than HTTP (for example Freemail) we cannot specify it in CENO's communications protocol. It is RS's responsibility to keep the state of the messages already sent or queued for sending and communication with RR.

Current implementation of RS and RR using Freemail:
  * RS creates a freemail message with the URL requested in the Subject.
  * RS uses SMTP protocol to send the freemail using the CENO client identity to an inbox the RR is listening
  * RR polls all inboxes for new freemails using IMAP
  * For every new freemail RR checks the validity of the URL in the subject and starts the procedure of requesting the bundle from BS. Once the bundle has been received, BI inserts it in the distributed cache.
  * There is no response from RR back to RS. The LCS in the user side will eventually find the inserted bundle in the distributed cache once the passive request is successful.

Comments:
  * Other RS-RR implementations might be synchronous over a secure channel, include RR->RS messages, include extra information etc.
  * It would be good to use HTTP Status Codes (200, 404 etc) in the responses
  * The protocol does not define how:
    * RS inserts the bundle in the LCS, in case the bundle is sent back as a response to [step 6](https://github.com/equalitie/ceno/blob/master/ceno-node/doc/CeNoProtocol.md#lookup-failure)
    * LCS searches in the distributed cache.
  * You might think passive requests in the distributed cache as persistent requests that complete as soon as the resource requested is found.

The updated specification document looks good :+1: though the differentiation between lookups in Local and Distributed cache adds unnecessary complexity, since both are managed internally by the LCS agent.

**Comment by redwire** [comment]
Thanks for the clarification here! I'll review and try to clear the parts of the spec about the local vs distributed cache lookups.

**Comment by redwire** [comment]
Closing since the protocol spec has been updated for a while and there aren't any more comments coming in.
