### ISSUE TITLE
CeNo-node should handle "DNF" from CeNo-plugin

### ISSUE THREAD

**Issue by vmon** [equalitie/ceno#8]
When CeNo-node receive "DNF" on the request put on port 3091, it should: 
1- Show a please wait page, with a timer that resend the request again when it times out.
2- check the "url being processed" list: if the requested is there then run 1 and end transaction. otherwise:
3- store the requested url in the "url being processed" list.
4- Resends the request on port 3092, Waits for response "DONE"
5- When "DONE" respose comes, drop the url from processing list.

**Comment by redwire** [comment]
Just a couple questions about all this.

1. In what format are these requests coming in, exactly? We're obviously not dealing with raw sockets, so we should think in terms of HTTP requests. In this case, it might make sense to have the server listening on port 3091 accept a "DNF" message on the route `/dnf`.
2. Rather than sharing state between three distinct HTTP servers all running on different ports, why not simply have different requests use different routes? Then CeNo-node can accept a regular request to bundle a page on `/` with the query `url=<url to bundle>`, a DNF message on `/dnf`, and a DONE message on the route `/done` and then both the latter requests can also accept the `url=<url to bundle>` query so that it can be determined for which responses the incoming request needs to be handled.
3. Shouldn't we treat the bundler server as something separate entirely? We can still do everything you mentioned, but just have CeNo-node send requests to the bundler server so that we don't lose our generality of being able to use any kind of bundling service as long as it responds to HTTP requests.
