### ISSUE TITLE
CeNo-node, Cache, and Bundler interface specification

### ISSUE THREAD

**Issue by redwire** [equalitie/ceno#9]
Here is a dump of the email I wrote to @billdoran, @vmon, and @misaakidis about the specification for the interaction between the three major components of CeNo that I have designed.

The sequence diagram referenced can be found [in my freenetinterface branch](https://raw.githubusercontent.com/redwire/ceno/d83adfdb07db7231a10005aab13b192bb4de3201/ceno-node/doc/commSeqDiag.png)

I've just finished designing what I think is a very reasonable
(relatively abstract) protocol to facilitate communication between the
CeNo client, Cache server, and Bundler/Transport.  I've designed the
protocol to use HTTP, since that is how most of the stack works already.

I've attached an image of a sequence diagram I did up to outline the
flow of the interactions.  Please have a quick look over it and refer
back to it as I go on to explain the steps and decisions I made
throughout the rest of this email.

First, some definitions:

1. The "User" in this case is the web browser- the human being who
initiates a request for a web page.
2. The "CeNo client" is the CeNo proxy server that serves bundled pages
in response to requests from User.
3. The "Cache server" is the server in charge of handling requests for
bundles, which currently runs on Freenet.
4. The "Bundler or Transport" is the bridge server that fetches pages
and compiles them into bundled documents.

Some formalities:

1. I adhere to HTTP's expectations that:
    1. GET requests are used to simply fetch documents/data; these
requests should not lead to changes on the server they are being
requested from.
    2. POST requests are used to make requests to pages that *do* lead
to changes on the server they are sent to.
2. JSON is used to encode responses that the CeNo client will have to
handle, since it is Javascript already and that is pretty standard
API-esque convention for Node.JS.
3. This document describes the more complicated scenario where a bundle
is *not* found stored on the Cache server.  Quite clearly, the case
where a bundle exists is finished after the first request to the Cache
server.

Now then, a detailed explanation of the process.

1. User sends a request for a page from CeNo client on the index route
(/), with the URL of the page encoded in the query string.
2. CeNoClient requests the bundle for the URL being requested from the
Cache server on the index route (/), using the same encoding.
3. Cache server checks if a bundle exists.
4. Cache server responds to CeNo client to inform it that no bundle was
found (DNF).
5. CeNo client sends User a "please wait" page which will periodically
re-request the original page requested by User. More on this later.
6. CeNo client also sends a request to Transport on the index route (/)
again with the URL encoded in the query string to initiate a bundle
creation process. This is a GET request because it does not require the
Transport store data- only that it start doing some work.
7. Transport responds to CeNo client with an ID corresponding to the
process handling its request.
8. Transport creates a bundle for the requested page.
9. Transport POSTs to Cache server on the store route (/store) to have
it store the new bundle.
10. Cache server stores the bundle.
11. Cache server responds to Transport to inform it that it has
completed storing the bundle.
12. Transport POSTs to CeNo client on the done route (/done) to inform
it that a process has completed.
13. CeNo client responds to Transport to confirm that it has
acknowledged that it is no longer waiting for the newly completed process.
14. User re-requests the page they originally requested just as in step 1.
15. As in step 2, CeNo client requests the bundle from Cache server.
16. Cache server checks for the bundle requested.
17. Cache server responds to CeNo client with the bundled page.
18. CeNo client serves the bundle to User.

Clarification:

1. At step 7, CeNo client will store the process ID it receives so that
it does not have to re-request the same page of either Cache server or
Transport should the same page be requested by User again.
2. Transport sends bundles to Cache server before CeNo client for three
reasons:
    1. So that it can respond (with a process ID) quickly to CeNo
client, making CeNo client able to keep track of requests being
processed and to leave it free to handle other User requests.
    2. So that the bundle can be guaranteed to be retrievable by Cache
server once CeNo client is informed that it has been prepared.
    3. So that CeNo client does not have to take any extra special steps
to request the bundle from Transport, and can instead re-request the
bundle from Cache server whenever User re-requests it.
3. Bundling is going to be a long process no matter what and the
expectation is that, over time, Bundler will be invoked less and less
for more popular, cached pages. All interactions are designed to be as
short and to-the-point as possible so that HTTP can be used seamlessly.
4. This design leaves CeNo client responsible for doing the bare minimum
amount of work/waiting possible so that it is free to quickly respond to
User in the case that it must reserve the "please wait" page.
5. Cache server is designed to behave most like a standard web service. 
It is possible to have bundles served to or requested from it from any
kind of clients with this approach.

That's it for now, everyone.  If anyone feels so inclined, feel free to
turn this email into an issue on Github for clearer discussion.  If you
have any questions, feel free to either email me back or hit me up on
IRC during my usual work hours (3:30 PM to 7:30 PM EST on Monday to Friday).

My focus is on the "please wait" page to be served to User as well as
the functionality of both CeNo client and Transport.  The majority of
the functionality of both of these things is already complete, and I
will begin implementing means of handling the protocol I have defined
here.  If any changes must be made, it will still be quite easy to do so.

**Comment by misaakidis** [comment]
Attaching @redwire's sequence diagram
![commseqdiag](https://cloud.githubusercontent.com/assets/2183693/5819408/3ab62b0a-a0c6-11e4-84aa-a1cfe312e457.png)

**Comment by misaakidis** [comment]
@redwire great job on explaining the steps and providing the sequence diagram.
Kudos for your proposal on separating GET and POST usage. Plus I'm in favor of JSON, since CeNo is implemented in Javascript and there are many available parsing/creation libraries for other programming languages. Nevertheless, all the above make individual parts look like RESTful services.

</br>
To sum up the ports each of the services is using:  
* User is using a browser to make GET requests. No background running service.
* CeNo client (ceno-node/src) is listening on :3090 for GET requests from User.
* Cache server (plugin-ceno) is listening on :3091 (GET) to initiate a cache lookup. Also on :3092 (POST) to start inserting a bundle.
* Bundler (ceno-node/bundler) is listening on :3093 (GET).

<hr>
All clear, my only objection being *direct communication (outside of freenet) between User and CeNo client*. Surveillance can know who is using CeNo (therefore Freenet in the background), what sites they are trying to access, and block access to CeNo in general. My understanding was that there would be two sides of the freenet plugin, one running on the user side and the other on the proxy/server side. This would inevitably though add complexity to the freenet plugins and make CeNo more dependent on freenet.

Some extra thoughts:  
* It'd be good if CeNo client and bundler were listening on consecutive ports (eg :3090 and :3091). I agree that a single port is enough for each of the services and partial functionality to use different routes as proposed on issue #8.
* Cache lookups need considerable time to return (at least in freenet). The "please wait" reply should be sent as soon as the GET url request has been received, acknowledging the request has been received.
* Requests should timeout. A queuing/promise mechanism is needed for this reason between the bundler and CeNo client/Cache Server.
* There is a RECENTLY_FAILED error that could cause problems in the second cache lookup. It is part of a freenet internal mechanism to early kill lookup requests for resources that previously failed (for example when a USK that was requested before was not found in the distributed cache).

**Comment by redwire** [comment]
Those are some really good point, @misaakidis.

I have a concern with the second of your extra thoughts regarding how quickly CeNo client would be expected to respond to User.  I definitely agree that we would like to have connections between User and CeNo client effectively closed as soon as possible so that CeNo client does not become overwhelmed. However, it my concern that if we have CeNo client always serve the "please wait" page immediately, then we have two issues with regards to how it later handles the bundle it requests of Cache server.

1. CeNo client will be made busy by requests to Cache server regardless of when it makes them. If we have CeNo client immediately respond to User with the "please wait" page, CeNo client would have to keep the bundle data it eventually receives in memory until User requests the page again. What if this request never comes? What if it just takes longer than usual for it to come?
2. Related to point 1 above, if we took the approach of further reducing the requirement for synchronization between CeNo client and Cache server so that Cache server would send a POST to CeNo client when it has retrieved a bundle from cache upon every request, Cache server would end up doing *a lot* more work than in the scheme I have outlined in cases where User has unusual timing for re-requests.

I believe I understand the motivation for your suggestion, but I worry about how it would scale as CeNo is used by more and more individuals with variably reliable network connections.

I suppose your third point addresses my concerns by introducing a Queue or Promise into the setting. I feel like we might be more specifically concerned with the ephemeral nature of HTTP requests and wonder what you think of the idea of not using HTTP at all.
